// ---------- File: app/download/page.tsx ----------
'use client';

export default function DownloadPage() {
  const handleDownload = () => {
    // Trigger download via anchor tag
    const link = document.createElement('a');
    link.href = 'http://localhost:5000/api/download/sample';
    link.download = 'sample.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <main className="p-6 space-y-4">
      <h1 className="text-2xl font-bold">File Download</h1>
      <p>Click below to download a file generated by the Flask API.</p>

      <button
        onClick={handleDownload}
        className="bg-purple-600 text-white px-4 py-2 rounded hover:bg-purple-700"
      >
        Download Sample File
      </button>
    </main>
  );
}
